config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :albums
  resources :photos, except: :index
  
  get 'photos' => 'photos#new'

  root 'users#new'
  get '/signup' => 'users#new'
  delete "user/:id" => "user#destroy"

  get '/login'    => 'sessions#new'
  post '/login'   => 'sessions#create'
  delete '/logout'=> 'sessions#destroy'

  

end

app/models/album.rb
class Album
  include Mongoid::Document
  field :name, type: String
  field :desc, type: String
  field :created, type: Date
  field :updated, type: Date

  embeds_many :photos, cascade_callbacks: true
  belongs_to :user

  mount_uploader :photo, PhotoUploader
  accepts_nested_attributes_for :photos
end

app/models/photo.rb
class Photo
  include Mongoid::Document
  field :caption, type: String

  embedded_in :album

  mount_uploader :image, PhotoUploader
end

app/models/user.rb
class User
  include Mongoid::Document
  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  attr_reader :password
  field :password_digest, type: String

	mount_uploader :image, AvatarUploader

  has_many :albums, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, presence: true, confirmation: true, length: { in: 6..20 }
  validates :password, confirmation: true, length:{in:6..20}, on: :update, allow_blank: true

   def password=(unencrypted_password)
    unless unencrypted_password.empty?
      # keep the unencrypted password in memory for a second
      @password = unencrypted_password
      # use BCrypt to encrypt our plain password into a digest
      # and store it in our database
     	self.password_digest = BCrypt::Password.create(unencrypted_password)
      end
    end

   def authenticate(unencrypted_password)
   	if BCrypt::Password.new(self.password_digest) == unencrypted_password
   		return self
   	else
   		return false
   	end
   end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index 
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @album.user = current_user
    # if !photo_params.nil?
    #   photo_params[:image].each {|p| @album.photos.new(image: p)}
    # end

    if @album.save
      redirect_to albums_path
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_path
    
  end

  def update
  end
  def date_published
    created_at.localtime.strftime("%A, %B %-d, %Y at %l:%M %p")
  end

  private
    def album_params
      params.require(:album).permit(:photo, :name, :desc, :date)
    end
    def photo_params
      params.require(:album).fetch(:photo, {}).permit(:caption, :image => [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def show
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
  end

  def new
    @album = Album.find(params[:album_id])
    @photo = Photo.new
    @photo = @album.photos.build
  end

  def create
    @album = Album.find(params[:album_id])   
    photo_create_params[:image].each {|p| @album.photos.new(image: p)}
    if @album.save
      redirect_to album_path(@album)
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
  end

  def update
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
    if @photo.update_attributes(photo_update_params)
      redirect_to album_photo_path
    else
      render "edit"
    end
  end

  def destroy
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
    if @photo.destroy
      redirect_to album_path(@album)
    else
      render "edit"
    end
  end

  def photo_update_params
    params.require(:photo).permit(:caption, :image => [])
  end 
  def photo_create_params
    params.require(:album).require(:photo).permit(:caption, :image => [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
		user = User.where(email: params[:login][:email]).first
		if user && user.authenticate(params[:login][:password])
			session[:user_id] = user.id.to_s
			session[:user_name] = user.first_name + " " + user.last_name
			redirect_to user
		else
			flash[:fail] = "Your log in failed"
			redirect_to login_path
		end
	end
	def destroy
		session.delete(:user_id)
		redirect_to login_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all 
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to users_path
		else
			flash[:fail] = "Sign in unsucessfull!"
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])

		foo = 'bar' # Won't be passed to View
		@another = 1; # @var will be passed into view
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to users_path
		else
			render "edit"
		end
	end


	private

		def user_params
			params.require(:user).permit(:image, :email, :first_name, :last_name, :password)
		end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
	# use what's stored in our session
  # to find which user we are
		@current_user ||= User.find(session[:user_id])
	end

  def logged_in?
    session[:user_id] != nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<h3>Here is where you will edit your albums</h3>

<h4>Coming Soon!</h4>

app/views/albums/index.html.erb
<!-- share navigation -->


<div class="jumbotron">
  <div class="index">
      <!-- form for rendering all albums -->
      <% current_user.albums.each do |a| %>
      <div>
        <%= link_to a.name, edit_album_path(a) %>
      </div>
      
        <% if @album %>
          <div><%=link_to (image_tag album.photos[0].image.url(:default)), album_path(album) %></div> 
        <% end %>

      <div>
        <%= link_to "Edit this album!", edit_album_path(a) %> 
      </div>  
      <div>
        <%= link_to "Delete this album!", a, method: :delete, data: { confirm: "Are you sure you want to delete this album?"} %>
      </div>  
    <% end %>
  </div> <!-- index album -->
</div> <!-- jumbotron -->

app/views/albums/new.html.erb
<!-- shared navigation -->

<div class="jumbotron">
  <div class="newalbum">

    <h2>Add a new album</h2>

    <%= form_for @album do |f| %>

    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.submit "Create Your Album" %>
    </div>
    <% end %>
  </div>
</div>

app/views/albums/show.html.erb
<div class="container-fluid content-body">
  <div class="row">
    <div class="form-group col-md-4 col-md-offset-4 text-center">
      <div>
      <h1><%= link_to @album.name %></h1>
      </div>
      <div>
        <%= @album.desc %>
      </div>
        <% @album.photos.each do |photo| %>
        <%= image_tag photo.image.url(:iphone) %>
      <% end %>
    </div> <!-- form-group -->
  </div> <!-- row -->
</div> <!-- container-fluid -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <h1>picha</h1>
  <h2>Share your stories with pictures</h2>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


  <header class="navbar  navbar-inverse">
    <div class="navbar-class">
      <div class="container">
        <ul class="nav navbar-nav">
          <!-- if logged in -->
        <% if session.has_key?(:user_id) %> 
          <li><%= session[:user_name] %></li>
          <li><%= link_to "Logout", logout_path, :method => :delete %></li>
          <li><%= link_to "Albums", albums_path %></li>
          <!-- if logged out -->
        <% else %>
          <li><%= link_to "Sign Up!", new_user_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
        </ul>
      </div>
    </div>
<!-- display inline in css, utilize css positioning (absolute or relative ) -->
  </header>
          <%= yield %>
</body>
</html>

app/views/photos/new.html.erb
<!-- shared navigation -->

<div class="jumbotron">
  <div class="newalbum">
    <h2>Add a new Picture/h2>
    <%= form_for @photo do |f| %>

      <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="add-photo">
        <h3>Add Photos</h3>

        <%= f.fields_for @album.photos do |photo_fields| %>

          <div>
            <%= photo_fields.file_field :image, multiple: true %>
          </div>

        <% end %>
      </div>

      <div>
        <%= f.submit "Upload" %>
      </div>
    <% end %>
  </div>
</div>

    <div class="add-photo">
      <h2>Add a new photo</h2>

      <%= f.fields_for @album.photos do |photo_fields| %>

        <div>
          <%= photo_fields.file_field :image, multiple: true %>
        </div>

      <% end %>
    </div>

app/views/photos/show.html.erb
<div class="container-fluid content-body">
  <div class="row">
    <div class="form-group col-md-4 col-md-offset-4 text-center">
      <div>
      <h1><%= @photo.name %></h1>
      </div>
      <div>
        <%= @photo.desc %>
      </div>
        <% @album.photos.each do |photo| %>
        <%= image_tag photo.image.url(:iphone) %>
      <% end %>
    </div> <!-- form-group -->
  </div> <!-- row -->
</div> <!-- container-fluid -->

app/views/users/_display_albums.html.erb
<div>
      <p><%= link_to("Create a new album", new_album_path) %></p>

      <% @user.albums.each do |album| %>
        <%= link_to album.name %>
        <% album.photos.each do |photo| %>
        <% end %>
      <% end %>
</div>

app/views/users/edit.html.erb
<!-- shared navigation -->


<div class="jumbotron">
	<div class="edit-user">
			<!-- form for edit user -->
		<%= form_for @user, :html => { :multipart => true } do |f| %>
			<div>
				<%= f.label :first_name %>
				<%= f.text_field :first_name %>
			</div>
			<div>
				<%= f.label :last_name %>
				<%= f.text_field :last_name %>
			</div>
			<div>
				<%= f.label :email %>
				<%= f.text_field :email %>
			</div>
			<div>
				<%= f.label :password %>
				<%= f.password_field :password %>
			</div>	
			<div>
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation %>
			</div>
			<div>
				<%= image_tag @user.image.url(:thumb) %>
			</div>
			<div>
				<%= f.label :avatar, "Change your face" %>
				<%= f.file_field :avatar %>
			</div>
			<div>
				<%= f.submit "Update your profile" %>
			</div>
		<% end %>
		<%= render "display_albums" %>
	</div> <!-- edit user -->
</div> <!-- jumbotron -->	

app/views/users/index.html.erb
<!--shared navigation -->

<div class="jumbotron">
	<div class="index">
			<!-- form for rendering all users -->
			<% @users.each do |u| %>
			<div>
				<%= u.first_name %> <%= u.last_name %>
			</div>
			<div>
				<%= link_to "Add a picture!", new_picture_path(u) %>
			</div>
			<div>
				<%= image_tag u.image.url(:thumb) %>	
			</div>
			<div>
				<%= u.email %>
			</div>
			<div>
				
				<%= link_to "Edit your profile!", edit_user_path(u) %>
				<%= link_to "Edit your album!", edit_album_path(u) %>
			</div>	
			<div>
				<%= link_to "Delete your profile!", user_path(u), method: :delete, data: { confirm: "Are you sure you want to delete this profile?"} %>
			</div>	
		<% end %>
	</div> <!-- index user -->
</div> <!-- jumbotron -->

app/views/users/new.html.erb
<!-- shared navigation -->


<div class="jumbotron">
	<div class="edit-user">
		<h2>Create an account!</h2>
			<!-- form for adding a user -->
		<%= form_for @user do |f| %>
			<div>
				<%= f.label :first_name %>
				<%= f.text_field :first_name %>
			</div>
			<div>
				<%= f.label :last_name %>
				<%= f.text_field :last_name %>
			</div>
			<div>
				<%= f.label :email %>
				<%= f.text_field :email %>
			</div>
			<div>
				<%= f.label :password %>
				<%= f.password_field :password %>
			</div>	
			<div>
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation %>
			</div>
			<div>
				<%= image_tag @user.image.url(:thumb) %>
			</div>
			<div>
				<%= f.file_field :image %>
			</div>
			<div>
				<%= f.submit "Sign Up" %>
			</div>
		<% end %>
	</div> <!-- edit-user -->
</div> <!-- jumbotron -->	

app/views/users/show.html.erb
<div class="container-fluid content-body">
	<div class="row">
		<div class="form-group col-md-4 col-md-offset-4 text-center">
			<h1>Your Account</h1>
			<h2> <%= @user.first_name %> <%= @user.last_name %> </h2>
			<ul>				
					<li> <%= @user.first_name %> </li>
					<li> <%= @user.last_name %> </li>
					<li> <%= @user.email %> </li>
					<li> <%= image_tag @user.image.url(:thumb) %>	</li>
					<li>  <%= render "display_albums" %> </li>
			</ul>
		</div> <!-- form-group -->
		<div>
				<%= link_to "Edit your profile!", edit_user_path %> 

				<%= link_to "Delete your profile!", user_path, method: :delete, data: { confirm: "Are you sure you want to delete this profile?"} %>
		</div>	
	</div> <!-- row -->
</div> <!-- container-fluid -->